spring.application.name=vacancy_manager

#Database configurattion
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin

# Hibernate configuration
# Informa ao Hibernate para atualizar e gerenciar o BD automaticamente, criando as tabelas necessárias com base nas entidades definidas no código.
spring.jpa.hibernate.ddl-auto=update